Repository womboai/wombo-bittensor-subnet, pull requests merged in 2024-04, with the labels that each got.

#31 Simplify async logic
  validator/validator/validator.py
Labels: bug

#40 Fix incorrect attribute access
  validator/validator/validator.py
Labels: bug_fix, Review effort [1-5]: 1

#41 Change scheduler settings to avoid oversaturation and bad quality
  gpu-pipeline/gpu_pipeline/pipeline.py
  validator/validator/validator.py
Labels: enhancement, Review effort [1-5]: 2

#42 Remove Validator API
  README.md
  client/setup.py
  gpu-pipeline/gpu_pipeline/pipeline.py
  image-generator/image_generator/main.py
  min_compute.yml
  miner/setup.py
  tensor/setup.py
  tensor/tensor/config.py
  validator-api/Dockerfile
  validator-api/README.md
  validator-api/build_docker.sh
  validator-api/example.env
  validator-api/run.sh
  validator-api/run_docker.sh
  validator-api/setup.py
  validator-api/setup.sh
  validator-api/tao.jpg
  validator-api/validator_api/__init__.py
  validator-api/validator_api/main.py
  validator/Dockerfile
  validator/example.env
  validator/setup.py
  validator/validator/miner_metrics.py
  validator/validator/reward.py
  validator/validator/similarity_score_pipeline.py
  validator/validator/validator.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#44 Add NSFW safety check to Validator
  gpu-pipeline/gpu_pipeline/pipeline.py
  gpu-pipeline/tao.jpg
  validator/setup.sh
  validator/validator/validator.py
Labels: enhancement, Review effort [1-5]: 3

#45 Increase penalty for failed requests, and make it cleaner
  validator/validator/miner_metrics.py
Labels: enhancement, Review effort [1-5]: 2

#46 Fix UID weighted random selection picking the same potentially UID several times
  neuron-selector/neuron_selector/uids.py
  validator/validator/validator.py
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#47 Add NSFW safety check to Validator(but to the right base this time mb)
  gpu-pipeline/gpu_pipeline/pipeline.py
  gpu-pipeline/tao.jpg
  validator/setup.sh
  validator/validator/validator.py
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#48 New autoupdate handling
  README.md
  client/Dockerfile
  client/build_docker.sh
  client/example.env
  client/run_docker.sh
  gpu-pipeline/Dockerfile
  image-generator/Dockerfile
  image-generator/build_docker.sh
  image-generator/example.env
  image-generator/run_docker.sh
  miner/Dockerfile
  miner/build_docker.sh
  miner/example.env
  miner/run_docker.sh
  neuron/Dockerfile
  tensor/Dockerfile
  validator/Dockerfile
  validator/build_docker.sh
  validator/example.env
  validator/run.sh
  validator/run_autoupdate.sh
  validator/run_docker.sh
  validator/run_pm2.sh
Labels: documentation, enhancement, Review effort [1-5]: 3

#49 Better handling for validators & miners
  gpu-pipeline/gpu_pipeline/pipeline.py
  image-generator/image_generator/main.py
  miner/miner/miner.py
  validator/validator/miner_metrics.py
  validator/validator/reward.py
  validator/validator/similarity_score_pipeline.py
  validator/validator/validator.py
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#50 Fix aiohttp client session init.
  miner/miner/miner.py
  validator/validator/miner_metrics.py
  validator/validator/validator.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#52 Fix idle miners not being punished
  validator/validator/miner_metrics.py
  validator/validator/validator.py
Labels: enhancement, Review effort [1-5]: 2

#51 Fix TCPConnector limit
  validator/validator/miner_metrics.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2
